version: '3.8'

services:
  lanzou-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lanzou-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../lanzou_api.py:/app/lanzou_api.py
      - ../templates:/app/templates
    environment:
      - TZ=Asia/Shanghai
